// Generated by CoffeeScript 1.7.1
(function() {
  var ObjectId, Settings, Tags, db, logger, metrics, mongojs, _ref;

  Settings = require('settings-sharelatex');

  logger = require('logger-sharelatex');

  mongojs = require('mongojs');

  db = mongojs((_ref = Settings.mongo) != null ? _ref.url : void 0, ['tags']);

  ObjectId = require('mongojs').ObjectId;

  metrics = require('metrics-sharelatex');

  module.exports = Tags = {
    getUserTags: function(user_id, callback) {
      if (callback == null) {
        callback = function(err, user) {};
      }
      return db.tags.find({
        "user_id": user_id
      }, callback);
    },
    createTag: function(user_id, name, callback) {
      if (callback == null) {
        callback = function(err, tag) {};
      }
      return db.tags.insert({
        user_id: user_id,
        name: name,
        project_ids: []
      }, function(err, tag) {
        if (err && err.code === 11000) {
          return db.tags.findOne({
            user_id: user_id,
            name: name
          }, callback);
        }
        return callback(err, tag);
      });
    },
    updateTagUserIds: function(old_user_id, new_user_id, callback) {
      var searchOps, updateOperation;
      if (callback == null) {
        callback = function(err, tag) {};
      }
      searchOps = {
        user_id: old_user_id
      };
      updateOperation = {
        "$set": {
          user_id: new_user_id
        }
      };
      return db.tags.update(searchOps, updateOperation, {
        multi: true
      }, callback);
    },
    addProjectToTag: function(user_id, tag_id, project_id, callback) {
      var e, insertOperation, searchOps;
      if (callback == null) {
        callback = function(error) {};
      }
      try {
        tag_id = ObjectId(tag_id);
      } catch (_error) {
        e = _error;
        return callback(e);
      }
      searchOps = {
        _id: tag_id,
        user_id: user_id
      };
      insertOperation = {
        "$addToSet": {
          project_ids: project_id
        }
      };
      return db.tags.update(searchOps, insertOperation, callback);
    },
    addProjectToTagName: function(user_id, name, project_id, callback) {
      var insertOperation, searchOps;
      if (callback == null) {
        callback = function(error) {};
      }
      searchOps = {
        name: name,
        user_id: user_id
      };
      insertOperation = {
        "$addToSet": {
          project_ids: project_id
        }
      };
      return db.tags.update(searchOps, insertOperation, {
        upsert: true
      }, callback);
    },
    removeProjectFromTag: function(user_id, tag_id, project_id, callback) {
      var deleteOperation, e, searchOps;
      if (callback == null) {
        callback = function(error) {};
      }
      try {
        tag_id = ObjectId(tag_id);
      } catch (_error) {
        e = _error;
        return callback(e);
      }
      searchOps = {
        _id: tag_id,
        user_id: user_id
      };
      deleteOperation = {
        "$pull": {
          project_ids: project_id
        }
      };
      return db.tags.update(searchOps, deleteOperation, callback);
    },
    removeProjectFromAllTags: function(user_id, project_id, callback) {
      var deleteOperation, searchOps;
      searchOps = {
        user_id: user_id
      };
      deleteOperation = {
        "$pull": {
          project_ids: project_id
        }
      };
      return db.tags.update(searchOps, deleteOperation, {
        multi: true
      }, callback);
    },
    deleteTag: function(user_id, tag_id, callback) {
      var e;
      if (callback == null) {
        callback = function(error) {};
      }
      try {
        tag_id = ObjectId(tag_id);
      } catch (_error) {
        e = _error;
        return callback(e);
      }
      return db.tags.remove({
        _id: tag_id,
        user_id: user_id
      }, callback);
    },
    renameTag: function(user_id, tag_id, name, callback) {
      var e;
      if (callback == null) {
        callback = function(error) {};
      }
      try {
        tag_id = ObjectId(tag_id);
      } catch (_error) {
        e = _error;
        return callback(e);
      }
      return db.tags.update({
        _id: tag_id,
        user_id: user_id
      }, {
        $set: {
          name: name
        }
      }, callback);
    }
  };

  ['getUserTags', 'createTag', 'addProjectToTag', 'removeProjectFromTag', 'removeProjectFromAllTags', 'deleteTag', 'renameTag'].map(function(_method) {
    return metrics.timeAsyncMethod(Tags, _method, 'mongo.Tags', logger);
  });

}).call(this);

//# sourceMappingURL=Tags.map
